In [8]:
import numpy as np

rng = np.random.default_rng(616)

price = (rng.random(10) * 10).round(2)

price

array([3.97, 8.66, 4.6 , 3.06, 5.74, 0.89, 8.82, 7.32, 7.32, 5.62])

In [10]:
inventory = rng.integers(0, 100, 10)

inventory

array([80, 33, 60,  6, 31, 35, 16, 20, 29, 43], dtype=int64)

In [14]:
inventory.mean()

35.3

In [16]:
inventory.sum()

353

In [18]:
inventory.max()

80

In [22]:
inventory.std()

20.48438429633656

In [40]:
(price * inventory).argmin()

3

In [44]:
price_2d = price.reshape(5,2)

price_2d

array([[3.97, 8.66],
       [4.6 , 3.06],
       [5.74, 0.89],
       [8.82, 7.32],
       [7.32, 5.62]])

In [46]:
price_2d.sum(axis=0)

array([30.45, 25.55])

In [56]:
price_2d.sum(axis=1).reshape(5,1)

array([[12.63],
       [ 7.66],
       [ 6.63],
       [16.14],
       [12.94]])