In [2]:
import numpy as np

rng = np.random.default_rng(616)

inventory = rng.integers(0, 100,10)

inventory

array([39, 39, 93, 86, 48, 46, 48, 30, 11, 57], dtype=int64)

In [4]:
inventory - 24

array([ 15,  15,  69,  62,  24,  22,  24,   6, -13,  33], dtype=int64)

In [8]:
(inventory / 2).dtype

dtype('float64')

In [16]:
price = (rng.random(10) * 10).round(2)

price

array([1.9 , 1.69, 4.74, 5.92, 4.25, 8.22, 3.8 , 0.22, 9.82, 5.5 ])

In [24]:
(price * inventory).sum()

2282.59

In [26]:
inventory_list = list(inventory)

In [28]:
inventory_list

[39, 39, 93, 86, 48, 46, 48, 30, 11, 57]

In [30]:
inventory_list + 2

TypeError: can only concatenate list (not "int") to list