In [3]:
import numpy as np

In [7]:
array = np.array(range(5))

In [9]:
array

array([0, 1, 2, 3, 4])

In [13]:
array_2d = np.array([range(5), range(5)])
array_2d + 1

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [15]:
array.shape

(5,)

In [17]:
array_2d.shape

(2, 5)

In [21]:
array.size

5

In [29]:
array_2d.T

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [31]:
array.ndim

1

In [33]:
array_2d.ndim

2

In [35]:
array.dtype

dtype('int32')

In [37]:
array_2d.dtype

dtype('int32')

In [39]:
np.array(['I', 'love', 'Python'])

array(['I', 'love', 'Python'], dtype='<U6')