In [6]:
import numpy as np

In [10]:
integer_array = np.arange(12)

In [12]:
integer_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
integer_array[1]

1

In [22]:
integer_array[-2]

10

In [24]:
integer_array[:5]

array([0, 1, 2, 3, 4])

In [28]:
integer_array[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
integer_array[::2]

array([ 0,  2,  4,  6,  8, 10])

In [34]:
new_array = integer_array.reshape(3,4)

In [36]:
new_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
new_array[:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
new_array[::]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
new_array[1:,:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
new_array[:,3]

array([ 3,  7, 11])

In [46]:
new_array[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [48]:
new_array[:,1:]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [52]:
new_array[2,1]

9