In [2]:
import numpy as np

In [6]:
rng = np.random.default_rng(12345)

rng.random(10)

array([0.22733602, 0.31675834, 0.79736546, 0.67625467, 0.39110955,
       0.33281393, 0.59830875, 0.18673419, 0.67275604, 0.94180287])

In [36]:
rng = np.random.default_rng(616)

rng.random(10)

array([0.39682145, 0.86568572, 0.46040359, 0.30599848, 0.57381588,
       0.08888468, 0.88194347, 0.73228387, 0.73215182, 0.56233394])

In [43]:
rng.integers(0,10,100)

array([4, 2, 0, 1, 6, 5, 0, 9, 2, 5, 5, 2, 1, 8, 6, 6, 5, 4, 4, 0, 0, 1,
       3, 8, 0, 2, 3, 5, 8, 6, 9, 8, 3, 9, 7, 1, 7, 9, 6, 4, 6, 0, 9, 8,
       1, 2, 5, 5, 9, 8, 3, 0, 9, 8, 3, 7, 5, 6, 4, 8, 0, 8, 0, 4, 9, 0,
       7, 7, 0, 7, 1, 5, 7, 7, 7, 8, 3, 7, 3, 8, 5, 7, 3, 1, 4, 7, 6, 7,
       5, 9, 5, 0, 9, 1, 5, 9, 5, 8, 6, 4], dtype=int64)

In [45]:
rng.normal(50,5,10)

array([40.40326606, 49.53532289, 53.3934452 , 48.38581526, 49.86478599,
       44.38062247, 53.06039076, 47.40586151, 47.17316538, 43.53380576])