In [2]:
import numpy as np

In [26]:
product_value = np.array(
    [205.4, 158.4, 138.4, 186.24, 6.24, 202.92, 106.44, 3.68, 26.15, 403.2]
)

product_value

array([205.4 , 158.4 , 138.4 , 186.24,   6.24, 202.92, 106.44,   3.68,
        26.15, 403.2 ])

In [14]:
np.sort(product_value)

array([  3.68,   6.24,  26.15, 106.44, 138.4 , 158.4 , 186.24, 202.92,
       205.4 , 403.2 ])

In [30]:
product_value.sort()

In [32]:
product_value

array([  3.68,   6.24,  26.15, 106.44, 138.4 , 158.4 , 186.24, 202.92,
       205.4 , 403.2 ])

In [22]:
product_value[-1]

403.2

In [24]:
product_value[::-1]

array([403.2 , 205.4 , 202.92, 186.24, 158.4 , 138.4 , 106.44,  26.15,
         6.24,   3.68])